[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c", "h"]
roots = ["compile_commands.json"]
comment-token = "//"
language-server = { command = "clangd" }
indent = { tab-width = 4, unit = " " }
formatter = { command = "clang-format", args = [] }


[[language]]
name = "cpp"
scope = "source.c"
injection-regex = "c"
file-types = ["cc", "cxx", "cpp", "h"]
roots = ["compile_commands.json"]
comment-token = "//"
language-server = { command = "clangd" }
indent = { tab-width = 4, unit = " " }
formatter = { command = "clang-format", args = [] }
